configurations:
# Generates the ConfigOptions Markdown documentation
- output: Docs/ConfigOptions.md
  parseDocumentation: true
  templates:
  - Sourcery/ConfigOptions.md.stencil
  sources:
  - Sources/CreateOptions/ConfigOptions.swift

# Generates the Decodable initializer with default values
- output: Sources/CreateOptions/ConfigOptions+DecodableWithDefault.swift
  templates:
  - Sourcery/DecodableWithDefault.swift.stencil
  sources:
  - Sources/CreateOptions/ConfigOptions.swift
