configurations:
- output: Docs/Options.md
  parseDocumentation: true
  templates:
  - Docs/Options.stencil
  sources:
  - Sources/CreateOptions/ConfigOptions.swift
- output: Sources/CreateOptions/ConfigOptions+DecodableWithDefault.swift
  templates:
  - Sources/CreateOptions/DecodableWithDefault.stencil
  sources:
  - Sources/CreateOptions/ConfigOptions.swift
