configurations:
- output: Docs/Options.md
  parseDocumentation: true
  templates:
  - Sourcery/Options.md.stencil
  sources:
  - Sources/CreateOptions/ConfigOptions.swift
- output: Sources/CreateOptions/ConfigOptions+DecodableWithDefault.swift
  templates:
  - Sourcery/DecodableWithDefault.swift.stencil
  sources:
  - Sources/CreateOptions/ConfigOptions.swift
